### ISSUE TITLE
Missing 'patch_n' keywords while trying the test data

### ISSUE THREAD

**Issue by Chelxen** [DeepXuan/Dn-Dp#11]
Hi, when I tried to run the provided test data with commands shown in the readme file , it told the keyerro 'patch_n'. Is there anything missing in the config file or something I missed?

**Comment by Chelxen** [comment]
Alright I found the solution in the closed issues but still don't know why.

**Comment by xiaoran007** [comment]
Hi, I noticed that patch_n is declared in the training config file with value 2, but not in the test profile. The author added a comment with the [paper](https://arxiv.org/abs/2207.04316) . I'm not sure this answers your question.
