### ISSUE TITLE
Denoising not working with test images for chest and liver

### ISSUE THREAD

**Issue by leejunseo97** [DeepXuan/Dn-Dp#6]
I downloaded this repository and pre-trained pth file. And then I tried to run the code from this repository, but encountered a couple of issues:

Initially, the code would not run due to the patch_n, patch_n_cond and mean_type options. To get it working, I had to modify the networks file to use their default options.
<img width="519" alt="image" src="https://github.com/DeepXuan/Dn-Dp/assets/68679618/e946f81a-bb93-4721-8211-74d325af8629">

After resolving the initial issue, I ran the code on test images for chest and liver. However, the denoising process does not seem to be working correctly on these images. (First imags are low images. second images are results of Dn_Chest_256 and Dn_Liver_128. Third images are results of Dn_Chest_256_512 and Dn_Liver_128_512

<img width="808" alt="image" src="https://github.com/DeepXuan/Dn-Dp/assets/68679618/9cc71de1-0cdd-486c-9350-846ca1121482">
<img width="814" alt="image" src="https://github.com/DeepXuan/Dn-Dp/assets/68679618/141d17ff-383f-41dd-8b85-beb4289c05e5">

**Comment by leejunseo97** [comment]
It works with 'epsilon' mean type!

**Comment by uigeunahn** [comment]
개추
